- name : install ngenix
  hosts: web
  vars:
    course: "devops with AWS"
    Duration: "120 hours"
    trainair: "siva kumar"
  tasks:
  - name: print the infomation
    ansible.builtin.debug:
      msg: "hi learning devops with aws {{course}}, duration {{Duration}}, training {{trainair}}"
      